services:
  mongo-service:
    container_name: ${MONGO_SERVICE_NAME}
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT_EXPOSE}:27017"
    networks:
      - app-net

  redis-service:
    container_name: ${REDIS_SERVICE_NAME}
    image: redis:6.2.5
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT_EXPOSE}:6379"
    networks:
      - app-net

  redis-ui-service:
    container_name: ${REDIS_UI_SERVICE_NAME}
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: ${REDIS_HOSTS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - "${REDIS_COMMANDER_PORT_EXPOSE}:8081"
    networks:
      - app-net

  loki-service:
    container_name: ${LOKI_SERVICE_NAME}
    image: grafana/loki:3.5.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-net

  promtail-service:
    container_name: ${PROMTAIL_SERVICE_NAME}
    image: grafana/promtail:2.9.3
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PROMTAIL_CONFIG_PATH}:/etc/promtail
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - ${LOKI_SERVICE_NAME}
    networks:
      - app-net

  prometheus-service:
    container_name: ${PROMETHEUS_SERVICE_NAME}
    image: prom/prometheus:v3.3.1
    volumes:
      - ${PROMETHEUS_CONFIG_PATH}:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - ${LOKI_SERVICE_NAME}
    networks:
      - app-net

  grafana-service:
    container_name: ${GRAFANA_SERVICE_NAME}
    image: grafana/grafana:12.0.1
    volumes:
      - ${GRAFANA_CONFIG_PATH}:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ${DASHBOARDS_PATH}:/etc/grafana/dashboards
    depends_on:
      - ${LOKI_SERVICE_NAME}
      - ${PROMETHEUS_SERVICE_NAME}
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_SECURITY_ADMIN_USER: ${GF_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
    ports:
      - "${GRAFANA_PORT_EXPOSE}:3000"
    networks:
      - app-net

  address-service:
    build: .
    container_name: ${ADDRESS_SERVICE_NAME}
    depends_on:
      - ${MONGO_SERVICE_NAME}
      - ${REDIS_SERVICE_NAME}
      - ${REDIS_UI_SERVICE_NAME}
    environment:
      SPRING_APPLICATION_NAME: ${ADDRESS_SERVICE_NAME}
      SPRING_APP_VERSION: ${PROJECT_VERSION}
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: ${APP_PORT_EXPOSE}
      SERVER_SERVLET_CONTEXT_PATH: /v1/api
      SPRING_MVC_LOCALE: pt_BR
      SPRING_SECURITY_USER_NAME: ${APPLICATION_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${APPLICATION_PASSWORD}
      SPRING_SECURITY_USER_ROLES: ${APPLICATION_ROLES}
      SPRING_APPLICATION_JSON: >
        {
          "management.endpoints.web.exposure.include": "prometheus,health,info,metrics",
          "management.metrics.export.prometheus.enabled": true,
          "management.metrics.distribution.percentiles-histogram.http.server.requests": true,
          "management.metrics.distribution.percentiles.http.server.requests": [0.50, 0.95, 0.99],
          "management.metrics.tags.application": "${SPRING_APPLICATION_NAME}",
          "management.metrics.tags.instance": "${HOSTNAME}"
        }
      SPRING_JACKSON_DATE_FORMAT: dd/MM/yyyy HH:mm:ss
      SPRING_JACKSON_TIME_ZONE: Brazil/East
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_CACHE_TYPE: redis
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 7d
      SPRING_CACHE_REDIS_CACHE_NULL_VALUES: false
      SPRING_DATA_REDIS_SERIALIZER_VALUE: GENERIC_JACKSON2_JSON
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_INITDB_HOST}:${MONGO_INITDB_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin&readPreference=primary&appname=app&directConnection=true&ssl=false
      OPENAPI_SERVER_URL: ${OPENAPI_SERVER_URL}
      FEIGN_CLIENT_VIACEP_URL: ${VIACEP_SERVICE}
      FEIGN_CLIENT_CONFIG_VIACEPCLIENT_READTIMEOUT: 1000
      FEIGN_CLIENT_CONFIG_VIACEPCLIENT_CONNECTTIMEOUT: 1000
      RESILIENCE4J_CIRCUITBREAKER_CONFIGS_DEFAULT_SLIDING_WINDOW_SIZE: 5
      RESILIENCE4J_CIRCUITBREAKER_CONFIGS_DEFAULT_FAILURE_RATE_THRESHOLD: 50
      RESILIENCE4J_CIRCUITBREAKER_CONFIGS_DEFAULT_WAIT_DURATION_IN_OPEN_STATE: 10s
      RESILIENCE4J_CIRCUITBREAKER_INSTANCES_VIACEPCLIENT_BASECONFIG: default
      RESILIENCE4J_RETRY_CONFIGS_DEFAULT_MAX_ATTEMPTS: 3
      RESILIENCE4J_RETRY_CONFIGS_DEFAULT_WAIT_DURATION: 500ms
      RESILIENCE4J_RETRY_INSTANCES_VIACEPCLIENT_BASECONFIG: default
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      LOG_LEVEL: ${LOG_LEVEL}
      LOGGING_LEVEL_ROOT: ${LOG_LEVEL}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${LOG_LEVEL}
      LOGGING_LEVEL_BR_COM_RD: ${LOG_LEVEL}
      LOGGING_LEVEL_COM_RD: ${LOG_LEVEL}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CACHE: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_PATTERN_LEVEL: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
    labels:
      compose_service: ${ADDRESS_SERVICE_NAME}
    ports:
      - "${APP_PORT_EXPOSE}:8887"
    networks:
      - app-net

volumes:
  redis:
  redis-config:

networks:
  app-net:
    driver: bridge
    name: ${NETWORK_NAME}
