scrape_configs:
  - job_name: "app"
    scrape_interval: 5s
    metrics_path: "/v1/api/actuator/prometheus"
    basic_auth:
      username: operation
      password: RNrYnqUgnCD3MdwG!
    static_configs:
      - targets: ["address-service:8887"]
