apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    isDefault: true
    jsonData:
      httpMethod: POST
    editable: true

  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    access: proxy
    url: http://loki-service:3100
    jsonData: {}
    editable: true
