name: CI/CD - Address Service

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./target/jacoco-aggregate/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: address-service-coverage
          fail_ci_if_error: true

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare deploy package
        run: |
          rm -rf deploy-package
          mkdir deploy-package

          cp -R \
            adapter \
            app \
            core \
            docs \
            etc \
            docker-compose.yml \
            Dockerfile \
            mvnw \
            mvnw.cmd \
            pom.xml \
            README.md \
            .env \
            checkstyle.xml \
            deploy-package/

          tar -czf address-service.tar.gz -C deploy-package .

      - name: Copy archive to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "address-service.tar.gz"
          target: ${{ secrets.VPS_DEPLOY_DIR }}

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e

            cd ${{ secrets.VPS_DEPLOY_DIR }}

            echo "Arquivos disponíveis antes de extrair:"
            ls -lah || true

            echo "Parando containers antigos (se existirem)..."
            docker compose down || true

            echo "Removendo arquivos antigos, exceto o tar.gz..."
            # Remove tudo, menos o arquivo .tar.gz
            find . -mindepth 1 -maxdepth 1 ! -name 'address-service.tar.gz' -exec rm -rf {} + || true

            echo "Arquivos após limpeza:"
            ls -lah || true

            echo "Extraindo arquivo tar.gz..."
            if [ -f address-service.tar.gz ]; then
              tar -xzf address-service.tar.gz
              echo "Extração concluída."
            else
              echo "Arquivo address-service.tar.gz não encontrado!"
              exit 1
            fi

            echo "Arquivos após extração:"
            ls -lah || true

            echo "Build sem cache..."
            docker compose build --no-cache

            echo "Subindo containers..."
            docker compose up -d

            echo "Status dos containers:"
            docker compose ps

            echo "Removendo arquivo tar.gz..."
            rm -f address-service.tar.gz || true

      - name: Cleanup local archive
        run: rm -f address-service.tar.gz
